USE ROLE ACCOUNTADMIN;  -- (or SYSADMIN if you normally work with that)

CREATE OR REPLACE DATABASE DEMO_DB;

USE DATABASE DEMO_DB;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE AIR_QUALITY (
    CITY STRING,
    AQI INTEGER,
    TIMESTAMP TIMESTAMP
);


SELECT * FROM DEMO_DB.PUBLIC.AIR_QUALITY ORDER BY TIMESTAMP DESC;